//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Addenda
    {
        public int IdAddenda { get; set; }
        public string nombreAddenda { get; set; }
        public string XML { get; set; }
        public Nullable<System.DateTime> FechaModificacion { get; set; }
        public string Usuario { get; set; }
        public Nullable<bool> Estado { get; set; }
    }
}
